project:
  type: website
  output-dir: docs
  title: "Environmental attitudes  study exploratory analysis"
  render:
    - index.qmd
#    - ELSA.qmd
#    - BES.qmd
    - ESS2.qmd
    - wvs.qmd
#    - ESS_uk.qmd


website:  
 sidebar:
     title: "Content"
     style: "floating"
     contents:
      - text: "Introduction"
        href: index.qmd
      - text: "European Social Survey Round 11"
        href: ESS2.qmd
      - text: "World Value Survey Wave 7"
        href: wvs.qmd

#bibliography: weighting_refs.bib
#nocite: |
#  @*
#jupyter: nbstata

execute:
  echo: false
  warning: false
  message: false
  cache: false
  



format:
    html: 
      code-overflow: scroll
      code-line-numbers: true
      page-layout: full
      toc: true
      toc-location: left
      highlight-style: arrow-light
      embed-resources: true
      smooth-scroll: true
      link-external-newwindow: true
      citations-hover: true
      footnotes-hover: true

mainfont: "Open Sans" 
sansfont: "Open Sans"
monofont: "Courier New"
monofontoptions: 'Scale=0.8'
pdf-engine: lualatex




